dynamically generate jobs.yaml

diff --git a/.github/workflows/worker.yaml b/.github/workflows/worker.yaml
--- a/.github/workflows/worker.yaml
+++ b/.github/workflows/worker.yaml
@@ -14,9 +14,24 @@ jobs:
       ROS_DISTRO: one
       DEB_DISTRO: jammy
       SEGMENT_DOWNLOAD_TIMEOUT_MINS: 10
+      JOBS_YAML: /home/runner/jobs.yaml
     steps:
       - name: Check out the repo
         uses: actions/checkout@v4
+      - name: Fetch job specification
+        id: fetch-jobs
+        uses: actions/cache/restore@v4
+        with:
+          path: ${{ env.JOBS_YAML }}
+          key: jobs-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
+          restore-keys: |
+            jobs-${{ github.sha }}-${{ github.run_id }}
+      - name: Verify jobs
+        run: |
+          if [ -z "${{ steps.fetch-jobs.outputs.cache-hit }}" ]; then
+            echo "Cache not found"
+            exit 1
+          fi
       - name: Use apt packages ${{ inputs.depends }}
         id: fetch-dependencies
         if: ${{ inputs.depends }}
@@ -35,14 +50,14 @@ jobs:
           fi
       - name: List repositories
         run: |
-          OPTS=$(yq ".\"${{ inputs.worker }}\".sbuild_options" jobs.yaml)
+          OPTS=$(yq ".\"${{ inputs.worker }}\".sbuild_options" ${{ env.JOBS_YAML }})
           [ "$OPTS" != "null" ] || OPTS=""
           [ -z "$OPTS" ] || echo "extra_sbuild_conf=$OPTS" >> $GITHUB_ENV
 
           QUERY=$(
             echo -n '{ "repositories": {';
             sep=""
-            yq '."${{ inputs.worker }}".jobs[]' jobs.yaml | while read repo; do
+            yq '."${{ inputs.worker }}".jobs[]' ${{ env.JOBS_YAML }} | while read repo; do
               echo -n "$sep \"$repo\": .repositories.\"$repo\""
               sep=","
             done
